import React from 'react';
export const SvgLoader = ({ className = '' }: { className?: string }) => (
    <svg
        xmlns="http://www.w3.org/2000/svg"
        className={`fenext_svg ${className}`}
        viewBox="0 0 100 100"
        preserveAspectRatio="xMidYMid"
    >
        <g transform="rotate(0 50 50)">
            <rect
                x="47.5"
                y="20.5"
                rx="2.5"
                ry="6.5"
                width="5"
                height="13"
                fill="currentColor"
            >
                <animate
                    attributeName="opacity"
                    values="1;0"
                    keyTimes="0;1"
                    dur="0.5555555555555556s"
                    begin="-0.5185185185185185s"
                    repeatCount="indefinite"
                ></animate>
            </rect>
        </g>
        <g transform="rotate(24 50 50)">
            <rect
                x="47.5"
                y="20.5"
                rx="2.5"
                ry="6.5"
                width="5"
                height="13"
                fill="currentColor"
            >
                <animate
                    attributeName="opacity"
                    values="1;0"
                    keyTimes="0;1"
                    dur="0.5555555555555556s"
                    begin="-0.48148148148148145s"
                    repeatCount="indefinite"
                ></animate>
            </rect>
        </g>
        <g transform="rotate(48 50 50)">
            <rect
                x="47.5"
                y="20.5"
                rx="2.5"
                ry="6.5"
                width="5"
                height="13"
                fill="currentColor"
            >
                <animate
                    attributeName="opacity"
                    values="1;0"
                    keyTimes="0;1"
                    dur="0.5555555555555556s"
                    begin="-0.4444444444444444s"
                    repeatCount="indefinite"
                ></animate>
            </rect>
        </g>
        <g transform="rotate(72 50 50)">
            <rect
                x="47.5"
                y="20.5"
                rx="2.5"
                ry="6.5"
                width="5"
                height="13"
                fill="currentColor"
            >
                <animate
                    attributeName="opacity"
                    values="1;0"
                    keyTimes="0;1"
                    dur="0.5555555555555556s"
                    begin="-0.4074074074074074s"
                    repeatCount="indefinite"
                ></animate>
            </rect>
        </g>
        <g transform="rotate(96 50 50)">
            <rect
                x="47.5"
                y="20.5"
                rx="2.5"
                ry="6.5"
                width="5"
                height="13"
                fill="currentColor"
            >
                <animate
                    attributeName="opacity"
                    values="1;0"
                    keyTimes="0;1"
                    dur="0.5555555555555556s"
                    begin="-0.37037037037037035s"
                    repeatCount="indefinite"
                ></animate>
            </rect>
        </g>
        <g transform="rotate(120 50 50)">
            <rect
                x="47.5"
                y="20.5"
                rx="2.5"
                ry="6.5"
                width="5"
                height="13"
                fill="currentColor"
            >
                <animate
                    attributeName="opacity"
                    values="1;0"
                    keyTimes="0;1"
                    dur="0.5555555555555556s"
                    begin="-0.3333333333333333s"
                    repeatCount="indefinite"
                ></animate>
            </rect>
        </g>
        <g transform="rotate(144 50 50)">
            <rect
                x="47.5"
                y="20.5"
                rx="2.5"
                ry="6.5"
                width="5"
                height="13"
                fill="currentColor"
            >
                <animate
                    attributeName="opacity"
                    values="1;0"
                    keyTimes="0;1"
                    dur="0.5555555555555556s"
                    begin="-0.2962962962962963s"
                    repeatCount="indefinite"
                ></animate>
            </rect>
        </g>
        <g transform="rotate(168 50 50)">
            <rect
                x="47.5"
                y="20.5"
                rx="2.5"
                ry="6.5"
                width="5"
                height="13"
                fill="currentColor"
            >
                <animate
                    attributeName="opacity"
                    values="1;0"
                    keyTimes="0;1"
                    dur="0.5555555555555556s"
                    begin="-0.25925925925925924s"
                    repeatCount="indefinite"
                ></animate>
            </rect>
        </g>
        <g transform="rotate(192 50 50)">
            <rect
                x="47.5"
                y="20.5"
                rx="2.5"
                ry="6.5"
                width="5"
                height="13"
                fill="currentColor"
            >
                <animate
                    attributeName="opacity"
                    values="1;0"
                    keyTimes="0;1"
                    dur="0.5555555555555556s"
                    begin="-0.2222222222222222s"
                    repeatCount="indefinite"
                ></animate>
            </rect>
        </g>
        <g transform="rotate(216 50 50)">
            <rect
                x="47.5"
                y="20.5"
                rx="2.5"
                ry="6.5"
                width="5"
                height="13"
                fill="currentColor"
            >
                <animate
                    attributeName="opacity"
                    values="1;0"
                    keyTimes="0;1"
                    dur="0.5555555555555556s"
                    begin="-0.18518518518518517s"
                    repeatCount="indefinite"
                ></animate>
            </rect>
        </g>
        <g transform="rotate(240 50 50)">
            <rect
                x="47.5"
                y="20.5"
                rx="2.5"
                ry="6.5"
                width="5"
                height="13"
                fill="currentColor"
            >
                <animate
                    attributeName="opacity"
                    values="1;0"
                    keyTimes="0;1"
                    dur="0.5555555555555556s"
                    begin="-0.14814814814814814s"
                    repeatCount="indefinite"
                ></animate>
            </rect>
        </g>
        <g transform="rotate(264 50 50)">
            <rect
                x="47.5"
                y="20.5"
                rx="2.5"
                ry="6.5"
                width="5"
                height="13"
                fill="currentColor"
            >
                <animate
                    attributeName="opacity"
                    values="1;0"
                    keyTimes="0;1"
                    dur="0.5555555555555556s"
                    begin="-0.1111111111111111s"
                    repeatCount="indefinite"
                ></animate>
            </rect>
        </g>
        <g transform="rotate(288 50 50)">
            <rect
                x="47.5"
                y="20.5"
                rx="2.5"
                ry="6.5"
                width="5"
                height="13"
                fill="currentColor"
            >
                <animate
                    attributeName="opacity"
                    values="1;0"
                    keyTimes="0;1"
                    dur="0.5555555555555556s"
                    begin="-0.07407407407407407s"
                    repeatCount="indefinite"
                ></animate>
            </rect>
        </g>
        <g transform="rotate(312 50 50)">
            <rect
                x="47.5"
                y="20.5"
                rx="2.5"
                ry="6.5"
                width="5"
                height="13"
                fill="currentColor"
            >
                <animate
                    attributeName="opacity"
                    values="1;0"
                    keyTimes="0;1"
                    dur="0.5555555555555556s"
                    begin="-0.037037037037037035s"
                    repeatCount="indefinite"
                ></animate>
            </rect>
        </g>
        <g transform="rotate(336 50 50)">
            <rect
                x="47.5"
                y="20.5"
                rx="2.5"
                ry="6.5"
                width="5"
                height="13"
                fill="currentColor"
            >
                <animate
                    attributeName="opacity"
                    values="1;0"
                    keyTimes="0;1"
                    dur="0.5555555555555556s"
                    begin="0s"
                    repeatCount="indefinite"
                ></animate>
            </rect>
        </g>
    </svg>
);
